# Generated by Django 4.2.11 on 2024-10-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("unit", models.CharField(max_length=50)),
                ("country_of_origin", models.CharField(max_length=100)),
                ("exported_to", models.JSONField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField()),
            ],
        ),
    ]
