# Generated by Django 4.2.11 on 2024-11-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks_app", "0002_rename_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
