# Generated by Django 4.2.11 on 2024-11-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks_app", "0003_stock_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="image_url",
            new_name="img",
        ),
    ]
